apiVersion: v1
kind: Service
metadata:
  name: gateway-api
spec:
  # O tipo NodePort expõe o serviço em uma porta estática em cada nó do cluster.
  # Ideal para acesso externo em desenvolvimento local.
  type: NodePort
  selector:
    app: gateway-api
  ports:
    - port: 8080
      targetPort: 8080
      # Acessaremos o gateway pela porta 30080 da nossa máquina
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  replicas: 1 # Em produção, poderíamos aumentar para 3 ou mais!
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: gateway-api:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080